name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          clean_workflows: failure
          # introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes
          # notable plugin for showcasing open source contributions
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          # activity plugin
          plugin_activity: yes
          
          
